# Credit to https://github.com/kasper573/mp/

name: 'Reusable Install'
description: 'Install node, pnpm and local node packages'
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version-file: 'package.json'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Install Packages
      shell: bash
      run: pnpm install
